apiVersion: apps/v1
kind: Deployment
metadata:
  name: keywell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keywell
  template:
    metadata:
      labels:
        app: keywell
    spec:
      containers:
      - image: okteto.dev/keywell:latest
        name: keywell
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "25c1a4e1-4993-4e48-a163-b66ca141632a"
        - name: Vless_Path
          value: "/vlfshtr4543t43"
        - name: Vmess_UUID
          value: "25c1a4e1-4993-4e48-a163-b66ca141632a"
        - name: Vmess_Path
          value: "/vmfshtr4543t43"
        - name: Share_Path
          value: "/rejaiolink"
